import type { Lesson } from '../types/content'

// Hand-authored lesson. Every explanation, hint, and feedback string is written
// by a human; answer checking is deterministic arithmetic. g = 9.8 m/s^2.
// Interactivity centers on the drop tower (live t / v / d readouts, Earth-vs-Moon)
// and the drop race, not the cannon.

export const freeFallLesson: Lesson = {
  id: 'free-fall',
  courseId: 'kinematics',
  order: 2,
  title: 'Free Fall & Gravity',
  concept: 'Everything falls at the same rate, gaining 9.8 m/s of speed every second.',
  estMinutes: 18,
  prerequisites: [],
  playable: true,
  intro: {
    hook: 'Drop a bowling ball and a marble at the same instant. Which one hits the floor first — and by how much?',
    objectives: [
      'Explain why mass does not change how fast something falls',
      'Use v = g·t to find falling speed at any moment',
      'Use d = ½·g·t² to find how far something has fallen',
      'Invert those formulas to find a time, and reason about other gravities',
    ],
    whyItMatters:
      'Free fall is the vertical half of every projectile. Nail it here, in a straight line, and the up-and-down part of any arc becomes easy.',
  },
  bigIdea:
    'Near Earth, gravity speeds everything up by the same 9.8 m/s each second, regardless of mass — so all objects fall together, faster and faster.',
  steps: [
    // ---------------- PREDICT ----------------
    {
      id: 'ff-predict',
      type: 'predict',
      phase: 'predict',
      concept: 'free-fall-rate',
      prompt:
        'You drop a heavy bowling ball and a light marble from the same height at the same moment (no air resistance). Which lands first?',
      choices: [
        { id: 'bowling', label: 'The heavy bowling ball' },
        { id: 'marble', label: 'The light marble' },
        { id: 'same', label: 'They land at the same time' },
      ],
      correctId: 'same',
      perChoiceFeedback: {
        bowling: 'It feels right because it is heavier, but no. Gravity speeds up every object at the same rate, whatever its mass.',
        marble: 'Lighter does not mean faster falling. Without air resistance, mass has no effect on the rate of fall.',
        same: 'Exactly. Galileo’s big idea: strip away air resistance and everything falls together.',
      },
      explanation:
        'Heavier objects feel more gravity, but they also need more force to speed up (more inertia). The two effects cancel exactly, so every object gains speed at the same 9.8 m/s per second.',
      takeaway: 'Mass does not change how fast something falls.',
    },

    // ---------------- EXPLORE ----------------
    {
      id: 'ff-tower-explore',
      type: 'interactive',
      phase: 'explore',
      widget: 'drop-tower',
      config: { height: 45 },
      title: 'Drop it and read the numbers',
      body: 'Release the ball and watch the three readouts. Notice the strobe dots: they start close together and spread apart as the ball speeds up. Try the Moon button — same idea, gentler gravity.',
      keyPoints: [
        'Speed climbs steadily the whole way down — it never stops accelerating.',
        'The strobe gaps grow because each second adds more speed.',
        'On the Moon (g = 1.62) everything is slower, but the pattern is identical.',
      ],
    },
    {
      id: 'ff-predict-speedup',
      type: 'predict',
      phase: 'explore',
      concept: 'gravity-accel',
      prompt: 'From watching the drop, what happens to the ball’s speed as it falls?',
      choices: [
        { id: 'const', label: 'It stays the same the whole way down' },
        { id: 'grows', label: 'It keeps increasing' },
        { id: 'peaks', label: 'It speeds up then slows near the ground' },
      ],
      correctId: 'grows',
      perChoiceFeedback: {
        const: 'Look at the speed readout — it climbs every moment. Falling is not constant-speed.',
        grows: 'Right — gravity keeps adding speed, so it falls faster and faster until it lands.',
        peaks: 'Nothing slows it down on the way; the speed only grows until impact.',
      },
      explanation: 'Gravity is a constant pull, so it keeps adding speed. The ball is fastest the instant before it lands.',
      takeaway: 'A falling object speeds up the entire way down.',
    },
    {
      id: 'ff-drop-race',
      type: 'interactive',
      phase: 'explore',
      widget: 'drop-race',
      title: 'Does sideways motion change the fall?',
      body: 'Now release a dropped ball next to a thrown one. Ignore the sideways travel and watch the heights: the dashed line connecting them stays perfectly level, and they touch down together. Change the throw speed — does either the timing or the level line change?',
      keyPoints: [
        'Both balls land at the SAME time — the level dashed line proves equal height the whole way.',
        'How LONG the fall takes depends only on the drop height, not the sideways speed.',
        'Throw speed changes only WHERE the thrown ball lands (how far out), never WHEN.',
      ],
    },

    // ---------------- BUILD: v = g t ----------------
    {
      id: 'ff-accel',
      type: 'concept',
      phase: 'build',
      concept: 'gravity-accel',
      title: 'Gravity is an accelerator',
      body: 'Gravity does not give an object a fixed speed — it adds speed continuously. Every second of falling adds another 9.8 m/s of downward velocity.',
      formula: {
        expr: 'v = g · t',
        terms: [
          { symbol: 'v', meaning: 'downward speed after falling (m/s)' },
          { symbol: 'g', meaning: 'gravity, 9.8 m/s²' },
          { symbol: 't', meaning: 'time spent falling (s)' },
        ],
      },
      keyPoints: ['After 1 s you fall at 9.8 m/s.', 'After 2 s, 19.6 m/s. The speed keeps climbing.'],
    },
    {
      id: 'ff-speed-numeric',
      type: 'numeric',
      phase: 'practice',
      concept: 'gravity-accel',
      prompt: 'You drop a rock from rest. How fast is it falling after 3 seconds? (v = g·t)',
      answer: 29.4,
      unit: 'm/s',
      tolerance: 0.5,
      min: 0,
      max: 100,
      hints: ['Use v = g·t with g = 9.8.', 'That is 9.8 × 3.'],
      explanation: 'v = g·t = 9.8 × 3 = 29.4 m/s. Each second adds another 9.8 m/s.',
      solution: ['Write v = g·t.', 'v = 9.8 × 3.', '= 29.4 m/s.'],
      takeaway: 'Falling speed grows by 9.8 m/s every second.',
    },
    {
      id: 'ff-speed-numeric-2',
      type: 'numeric',
      phase: 'practice',
      concept: 'gravity-accel',
      prompt: 'Starting from rest, how fast is an object falling after 1.5 seconds?',
      answer: 14.7,
      unit: 'm/s',
      tolerance: 0.5,
      min: 0,
      max: 100,
      hints: ['v = g·t.', '9.8 × 1.5.'],
      explanation: 'v = 9.8 × 1.5 = 14.7 m/s.',
      solution: ['v = g·t = 9.8 × 1.5.', '= 14.7 m/s.'],
      takeaway: 'v = g·t works at any instant of the fall.',
    },
    {
      id: 'ff-invert-time',
      type: 'numeric',
      phase: 'practice',
      concept: 'gravity-accel',
      prompt: 'Rearrange v = g·t. How long does it take a dropped object to reach 49 m/s? (t = v / g)',
      answer: 5,
      unit: 's',
      tolerance: 0.2,
      min: 0,
      max: 20,
      hints: ['Solve v = g·t for t: t = v / g.', '49 ÷ 9.8.'],
      explanation: 't = v / g = 49 / 9.8 = 5 s.',
      solution: ['t = v / g.', 't = 49 / 9.8.', '= 5 s.'],
      takeaway: 'The same formula runs backward to find a time.',
    },

    // ---------------- BUILD: d = 1/2 g t^2 ----------------
    {
      id: 'ff-distance',
      type: 'concept',
      phase: 'build',
      concept: 'fall-distance',
      title: 'How far has it fallen?',
      body: 'Because the speed is always changing, distance does not grow steadily — it grows with the square of time. Fall twice as long and you cover four times the distance.',
      formula: {
        expr: 'd = ½ · g · t²',
        terms: [
          { symbol: 'd', meaning: 'distance fallen (m)' },
          { symbol: 'g', meaning: 'gravity, 9.8 m/s²' },
          { symbol: 't', meaning: 'time spent falling (s)' },
        ],
      },
      keyPoints: ['After 1 s: 4.9 m. After 2 s: 19.6 m. After 3 s: 44.1 m.', 'The t² is why a long fall covers ground so fast.'],
    },
    {
      id: 'ff-distance-numeric',
      type: 'numeric',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'A ball falls from rest for 2 seconds. How far does it drop? (d = ½·g·t²)',
      answer: 19.6,
      unit: 'm',
      tolerance: 0.6,
      min: 0,
      max: 200,
      hints: ['Use d = ½·g·t² with g = 9.8.', 'That is 0.5 × 9.8 × 2².'],
      explanation: 'd = ½ × 9.8 × 2² = 0.5 × 9.8 × 4 = 19.6 m.',
      solution: ['Write d = ½·g·t².', 'd = 0.5 × 9.8 × (2)².', '= 0.5 × 9.8 × 4.', '= 19.6 m.'],
      takeaway: 'Distance fallen grows with the square of time.',
    },
    {
      id: 'ff-distance-numeric-2',
      type: 'numeric',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'How far does the same ball fall in 3 seconds?',
      answer: 44.1,
      unit: 'm',
      tolerance: 1,
      min: 0,
      max: 300,
      hints: ['d = ½·g·t², now t = 3.', '0.5 × 9.8 × 9.'],
      explanation: 'd = 0.5 × 9.8 × 3² = 0.5 × 9.8 × 9 = 44.1 m.',
      solution: ['d = 0.5 × 9.8 × (3)².', '= 0.5 × 9.8 × 9.', '= 44.1 m.'],
      takeaway: 'Tripling the time gives nine times the distance (3²).',
    },
    {
      id: 'ff-drop-target-1',
      type: 'drop-target',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'Make the fall last exactly 2.0 seconds. Slide the drop height, watch the fall-time readout, then drop to feel it.',
      targetTime: 2.0,
      tolerance: 0.15,
      hints: ['Fall time t = √(2h/g); rearranged, h = ½·g·t².', 'For 2 s: h = ½ × 9.8 × 2² ≈ 20 m.'],
      explanation: 'Since t = √(2h/g), a 2.0 s fall needs h = ½·g·t² = ½ × 9.8 × 4 ≈ 20 m.',
      takeaway: 'Choosing the drop height sets the fall time.',
    },
    {
      id: 'ff-stop-1',
      type: 'stop-fall',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'Release the ball and hit Stop the instant it reaches the 20 m line. Trust your eyes — it keeps speeding up as it drops.',
      targetDistance: 20,
      height: 45,
      tolerance: 4,
      hints: ['The ball covers ground faster the longer it falls.', 'It reaches 20 m at about t = 2 s (½·9.8·2² ≈ 20).'],
      explanation: 'It passes 20 m at t = √(2·20/9.8) ≈ 2.0 s, already moving ~20 m/s — so the timing window is short.',
      takeaway: 'Falling accelerates: equal distances take less and less time.',
    },
    {
      id: 'ff-square-mcq',
      type: 'mcq',
      phase: 'build',
      concept: 'fall-distance',
      prompt: 'If you double the falling time, the distance fallen becomes...',
      choices: [
        { id: '2x', label: 'Twice as much' },
        { id: '4x', label: 'Four times as much' },
        { id: 'same', label: 'The same' },
      ],
      correctId: '4x',
      perChoiceFeedback: {
        '2x': 'Distance is not proportional to time here — it is proportional to time squared.',
        '4x': 'Right: d ∝ t², and 2² = 4, so double the time → four times the distance.',
        same: 'It definitely grows — and faster than linearly, because of the t².',
      },
      explanation: 'Since d = ½g·t², distance scales with t². Doubling t multiplies distance by 2² = 4.',
      takeaway: 'Double the time → quadruple the distance.',
    },
    {
      id: 'ff-moon-explore',
      type: 'interactive',
      phase: 'practice',
      widget: 'drop-tower',
      config: { height: 30 },
      title: 'Switch gravity and watch',
      body: 'Drop on Earth, then tap Moon and drop again. Same ball, same height — notice how much more slowly the time, speed, and distance readouts climb when g is smaller.',
      keyPoints: [
        'Moon gravity (1.62) is about one-sixth of Earth’s.',
        'Smaller g → gentler speed-up and a longer fall.',
        'The formulas are identical; only the value of g changes.',
      ],
    },
    {
      id: 'ff-invert-distance',
      type: 'numeric',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'A ball is dropped from a 44.1 m cliff. How long until it hits the ground? (t = √(2d/g))',
      answer: 3,
      unit: 's',
      tolerance: 0.2,
      min: 0,
      max: 20,
      hints: ['Solve d = ½·g·t² for t: t = √(2d/g).', '√(2 × 44.1 / 9.8) = √9.'],
      explanation: 't = √(2d/g) = √(2·44.1/9.8) = √9 = 3 s.',
      solution: ['t = √(2d/g).', 't = √(2 × 44.1 / 9.8).', '= √9.', '= 3 s.'],
      takeaway: 'Invert the distance formula to find a fall time.',
    },
    {
      id: 'ff-drop-target-2',
      type: 'drop-target',
      phase: 'practice',
      concept: 'fall-distance',
      prompt: 'Now dial in a longer fall: set the height so the drop lasts 3.0 seconds.',
      targetTime: 3.0,
      tolerance: 0.2,
      hints: ['Use h = ½·g·t².', 'For 3 s: ½ × 9.8 × 3² ≈ 44 m.'],
      explanation: 'h = ½·g·t² = ½ × 9.8 × 9 ≈ 44 m produces a 3.0 s fall.',
      takeaway: 'Longer falls need taller drops — and height grows with t².',
    },

    // ---------------- air resistance + other gravity ----------------
    {
      id: 'ff-air',
      type: 'mcq',
      phase: 'build',
      concept: 'free-fall-rate',
      prompt: 'On the Moon, an astronaut drops a hammer and a feather together. What happens?',
      choices: [
        { id: 'hammer', label: 'The hammer lands well before the feather' },
        { id: 'feather', label: 'The feather drifts and lands last' },
        { id: 'same', label: 'They land at the same time' },
      ],
      correctId: 'same',
      perChoiceFeedback: {
        hammer: 'That is what happens on Earth — but only because of air. The Moon has almost none.',
        feather: 'On Earth, yes. On the airless Moon there is nothing to slow the feather down.',
        same: 'Correct — this was famously done on Apollo 15. With no air, free fall is truly equal.',
      },
      explanation:
        'Air resistance is what makes feathers flutter on Earth. Remove the air (as on the Moon) and the pure rule shows through: everything falls at the same rate.',
      takeaway: 'Air resistance — not gravity — is what separates a feather from a hammer.',
    },
    {
      id: 'ff-moon-numeric',
      type: 'numeric',
      phase: 'practice',
      concept: 'gravity-accel',
      prompt: 'On the Moon, gravity is g = 1.62 m/s². How fast is a dropped tool moving after 5 seconds?',
      answer: 8.1,
      unit: 'm/s',
      tolerance: 0.3,
      min: 0,
      max: 50,
      hints: ['Same formula, v = g·t, but use the Moon’s g.', '1.62 × 5.'],
      explanation: 'v = g·t = 1.62 × 5 = 8.1 m/s — much gentler than Earth’s 49 m/s.',
      solution: ['v = g·t with g = 1.62.', 'v = 1.62 × 5.', '= 8.1 m/s.'],
      takeaway: 'The formulas are universal; only g changes between worlds.',
    },
    {
      id: 'ff-two-formulas',
      type: 'concept',
      phase: 'build',
      concept: 'fall-distance',
      title: 'Keep the two formulas straight',
      body: 'Before the final recall: falling has two companion formulas, and mixing them up is the most common slip. One tells you how FAST it is going; the other how FAR it has dropped.',
      formula: {
        expr: 'v = g · t\nd = ½ · g · t²',
        terms: [
          { symbol: 'v', meaning: 'speed after time t (m/s)' },
          { symbol: 'd', meaning: 'distance fallen (m)' },
          { symbol: 'g', meaning: 'gravity, 9.8 m/s²' },
        ],
      },
      keyPoints: ['Speed grows linearly with time (g·t).', 'Distance grows with time squared (½·g·t²).'],
    },

    // ---------------- MASTER ----------------
    {
      id: 'ff-recall',
      type: 'recall',
      phase: 'master',
      concept: 'free-fall-rate',
      prompt: 'From memory: two objects of very different mass are dropped together in a vacuum. Which reaches the ground first?',
      choices: [
        { id: 'heavy', label: 'The heavier one' },
        { id: 'light', label: 'The lighter one' },
        { id: 'same', label: 'They arrive together' },
      ],
      correctId: 'same',
      explanation: 'Together. In a vacuum there is no air to treat them differently, and gravity speeds up all masses at the same rate.',
      takeaway: 'In free fall, mass is irrelevant.',
    },
    {
      id: 'ff-recall-2',
      type: 'recall',
      phase: 'master',
      concept: 'gravity-accel',
      prompt: 'From memory: which formula gives the speed of a dropped object after time t?',
      choices: [
        { id: 'gt', label: 'v = g · t' },
        { id: 'half', label: 'v = ½ · g · t²' },
        { id: 'overg', label: 'v = t / g' },
      ],
      correctId: 'gt',
      explanation: 'v = g·t gives speed; ½g·t² gives distance fallen. Keep the two straight.',
      takeaway: 'Speed: v = g·t. Distance: d = ½g·t².',
    },
    {
      id: 'ff-synthesis',
      type: 'mcq',
      phase: 'master',
      concept: 'fall-distance',
      prompt:
        'Two stones are dropped: stone B falls for twice as long as stone A before landing. How do their fall distances compare?',
      choices: [
        { id: 'twice', label: 'B falls twice as far' },
        { id: 'four', label: 'B falls four times as far' },
        { id: 'same', label: 'They fall the same distance' },
      ],
      correctId: 'four',
      perChoiceFeedback: {
        twice: 'Distance is not linear in time here — it depends on t².',
        four: 'Right — d ∝ t², so twice the time means 2² = 4 times the distance.',
        same: 'Different times mean different distances; the longer fall covers much more.',
      },
      explanation: 'd = ½g·t², so distance scales with t². Twice the time → 4× the distance.',
      takeaway: 'Fall distance always scales with time squared.',
    },
  ],
}
