import type { Lesson } from '../types/content'

// Hand-authored lesson. Every explanation, hint, and feedback string is written
// by a human; checking is deterministic. This is the foundation lesson: it uses
// the position-time grapher (no cannon) so motion ideas come from what you see.

export const positionVelocityLesson: Lesson = {
  id: 'position-velocity',
  courseId: 'kinematics',
  order: 1,
  title: 'Position & Velocity',
  concept: 'Where something is, how far it moved, and how fast — with direction.',
  estMinutes: 18,
  prerequisites: [],
  playable: true,
  intro: {
    hook: 'Two runners both clock "8 meters per second." One is pulling away from you; the other is heading straight back. Are they really moving the same way?',
    objectives: [
      'Tell the difference between speed and velocity',
      'Separate distance travelled from displacement',
      'Read velocity as the slope of a position-time graph',
      'Compute average velocity as displacement over time',
    ],
    whyItMatters:
      'Position and velocity are the vocabulary of all motion. Get them precise here and every later lesson — free fall, projectiles, aiming — clicks into place.',
  },
  bigIdea:
    'Velocity is displacement over time WITH a direction. On a position-time graph it is simply the slope: steeper means faster, downhill means going backward.',
  steps: [
    // ---------------- PREDICT ----------------
    {
      id: 'pv-hook',
      type: 'predict',
      phase: 'predict',
      concept: 'speed-vs-velocity',
      prompt:
        'Two cars each read 60 km/h on the speedometer. One drives due north, the other due south. Do they have the same velocity?',
      choices: [
        { id: 'yes', label: 'Yes — same number on the speedometer' },
        { id: 'no', label: 'No — they move in opposite directions' },
        { id: 'depends', label: 'Only if they are on the same road' },
      ],
      correctId: 'no',
      perChoiceFeedback: {
        yes: 'Same speed, yes — but velocity also carries direction, and theirs are opposite.',
        no: 'Exactly. Velocity = speed + direction. Opposite directions mean different velocities.',
        depends: 'The road does not matter; the directions are opposite, so the velocities differ.',
      },
      explanation:
        'Speed is just "how fast" (a number). Velocity is "how fast, and which way." Same speed, opposite directions = different velocities.',
      takeaway: 'Velocity carries a direction; speed does not.',
      game: { kind: 'two-runners', config: { v1: 8, v2: -8 } },
    },

    // ---------------- EXPLORE ----------------
    {
      id: 'pv-graph-explore',
      type: 'interactive',
      phase: 'explore',
      widget: 'motion-graph',
      config: { velocity: 4 },
      title: 'Velocity is a slope',
      body: 'This is a position-time graph: time runs sideways, position runs up. Set a velocity and press Play to watch a dot trace the line. Try a big velocity, a small one, and even a negative one.',
      keyPoints: [
        'Bigger velocity → steeper line (position climbs faster).',
        'Negative velocity → the line slopes downhill (moving backward).',
        'Constant velocity always makes a straight line.',
      ],
    },
    {
      id: 'pv-predict-slope',
      type: 'predict',
      phase: 'explore',
      concept: 'velocity-graph',
      prompt: 'On a position-time graph, a steeper upward line means the object is...',
      choices: [
        { id: 'faster', label: 'Moving faster' },
        { id: 'slower', label: 'Moving slower' },
        { id: 'still', label: 'Standing still' },
      ],
      correctId: 'faster',
      perChoiceFeedback: {
        faster: 'Right — more position covered per second is a steeper slope.',
        slower: 'Try the slider: a steeper line covered ground faster, not slower.',
        still: 'Standing still is a flat line. Steeper means more motion, not less.',
      },
      explanation:
        'Slope = rise over run = change in position over change in time = velocity. Steeper slope, larger velocity.',
      takeaway: 'Steeper position-time line = faster.',
      game: { kind: 'motion-graph', config: { velocity: 6 } },
    },

    // ---------------- BUILD: speed vs velocity ----------------
    {
      id: 'pv-speed-velocity',
      type: 'concept',
      phase: 'build',
      concept: 'speed-vs-velocity',
      title: 'Speed vs. velocity',
      body: 'These two words are casual twins in everyday talk, but physics keeps them apart. One is a plain number; the other also points somewhere.',
      keyPoints: [
        'Speed: how fast, a single positive number (a "scalar").',
        'Velocity: how fast AND in what direction (a "vector").',
        'A sign (+/−) is the simplest way to show direction along a line.',
      ],
    },
    {
      id: 'pv-mcq-vector',
      type: 'mcq',
      phase: 'build',
      concept: 'speed-vs-velocity',
      prompt: 'Which statement gives a velocity, not just a speed?',
      choices: [
        { id: 'a', label: '"The train moved at 30 m/s."' },
        { id: 'b', label: '"The train moved at 30 m/s, heading east."' },
        { id: 'c', label: '"The train travelled 30 meters."' },
      ],
      correctId: 'b',
      perChoiceFeedback: {
        a: 'That is a speed — a number with no direction.',
        b: 'Yes — it has both a size (30 m/s) and a direction (east). That is a velocity.',
        c: 'That is a distance, not a rate at all.',
      },
      explanation: 'A velocity must state a direction. "30 m/s east" qualifies; "30 m/s" alone is only speed.',
      takeaway: 'No direction stated → it is speed, not velocity.',
      game: { kind: 'two-runners', config: { v1: 5, v2: -5 } },
    },

    // ---------------- BUILD: distance vs displacement ----------------
    {
      id: 'pv-displacement-concept',
      type: 'concept',
      phase: 'build',
      concept: 'displacement',
      title: 'Distance vs. displacement',
      body: 'Walk 3 m east, then 1 m back west. Your feet covered 4 m of ground (distance), but you only ended up 2 m from where you started (displacement). Displacement is the straight-line change in position, with direction.',
      keyPoints: [
        'Distance: total ground covered, always adds up.',
        'Displacement: final position minus start position (can be negative or zero).',
        'A round trip has lots of distance but ZERO displacement.',
      ],
    },
    {
      id: 'pv-displacement-mcq',
      type: 'mcq',
      phase: 'build',
      concept: 'displacement',
      prompt: 'You walk 5 m east, then 2 m west. What is your displacement from the start?',
      choices: [
        { id: '7', label: '7 m' },
        { id: '3e', label: '3 m east' },
        { id: '3w', label: '3 m west' },
      ],
      correctId: '3e',
      perChoiceFeedback: {
        '7': '7 m is the total distance walked, not the displacement.',
        '3e': 'Right: 5 east − 2 west = 3 m east from where you began.',
        '3w': 'Check the direction — you went farther east than west, so you end up east.',
      },
      explanation: 'Displacement = 5 m east − 2 m west = 3 m east. Distance walked was 7 m, but net position changed by 3 m east.',
      takeaway: 'Displacement is net change in position, not total ground covered.',
      game: { kind: 'two-runners', config: { v1: 5, v2: -2 } },
    },

    // ---------------- BUILD: average velocity ----------------
    {
      id: 'pv-avg-formula',
      type: 'concept',
      phase: 'build',
      concept: 'avg-velocity',
      title: 'Average velocity',
      body: 'Average velocity packs the whole trip into one number: how much your position changed, divided by how long it took.',
      formula: {
        expr: 'v_avg = Δx / Δt',
        terms: [
          { symbol: 'v_avg', meaning: 'average velocity (m/s)' },
          { symbol: 'Δx', meaning: 'displacement (final − start position)' },
          { symbol: 'Δt', meaning: 'time taken (s)' },
        ],
      },
      keyPoints: [
        'Use displacement, not distance — direction matters.',
        'If you end where you started, Δx = 0, so average velocity = 0.',
      ],
    },
    {
      id: 'pv-avg-numeric-1',
      type: 'numeric',
      phase: 'practice',
      concept: 'avg-velocity',
      prompt: 'A cyclist rides 100 m straight down a path in 20 s. What is the average velocity?',
      answer: 5,
      unit: 'm/s',
      tolerance: 0.2,
      min: 0,
      max: 50,
      hints: ['Use v_avg = Δx / Δt.', 'That is 100 ÷ 20.'],
      explanation: 'v_avg = Δx / Δt = 100 m / 20 s = 5 m/s.',
      solution: ['Write v_avg = Δx / Δt.', 'v_avg = 100 / 20.', '= 5 m/s.'],
      takeaway: 'Average velocity = displacement ÷ time.',
      game: { kind: 'track-trip', config: { velocity: 5 } },
    },

    // ---------------- BUILD: velocity from a graph ----------------
    {
      id: 'pv-slope-concept',
      type: 'concept',
      phase: 'build',
      concept: 'velocity-graph',
      title: 'Reading velocity off a graph',
      body: 'On a position-time graph the velocity is literally the slope of the line: how much the position rises for each second of run.',
      formula: {
        expr: 'v = (x₂ − x₁) / (t₂ − t₁)',
        terms: [
          { symbol: 'v', meaning: 'velocity (slope of the line)' },
          { symbol: 'x₂ − x₁', meaning: 'change in position (rise)' },
          { symbol: 't₂ − t₁', meaning: 'change in time (run)' },
        ],
      },
      keyPoints: ['A straight line = constant velocity.', 'A flat line = not moving.', 'A downhill line = negative velocity.'],
    },
    {
      id: 'pv-graph-backward',
      type: 'interactive',
      phase: 'build',
      widget: 'motion-graph',
      config: { velocity: -4 },
      title: 'What does backward look like?',
      body: 'Set the velocity negative and play. Notice the line heads downhill — the position decreases over time. Then nudge it to zero: a flat line, no motion at all.',
      keyPoints: [
        'Negative velocity → line slopes down → position shrinking.',
        'Zero velocity → perfectly flat line.',
        'The sign of the slope is the direction of travel.',
      ],
    },
    {
      id: 'pv-graph-numeric',
      type: 'numeric',
      phase: 'practice',
      concept: 'velocity-graph',
      prompt:
        "On a position-time graph, an object goes from 0 m to 40 m over 5 seconds in a straight line. What is its velocity?",
      answer: 8,
      unit: 'm/s',
      tolerance: 0.3,
      min: 0,
      max: 50,
      hints: ['Velocity is the slope: rise ÷ run.', 'Rise = 40 m, run = 5 s.'],
      explanation: 'v = (40 − 0) / (5 − 0) = 40 / 5 = 8 m/s.',
      solution: ['Slope = rise / run.', 'v = 40 / 5.', '= 8 m/s.'],
      takeaway: 'Velocity from a graph = rise ÷ run.',
      game: { kind: 'motion-graph', config: { velocity: 8 } },
    },
    {
      id: 'pv-graph-target-1',
      type: 'graph-target',
      phase: 'practice',
      concept: 'velocity-graph',
      prompt: 'Your turn to draw it. Drag the velocity until your position-time line passes through the marked point.',
      target: { t: 4, x: 24 },
      tolerance: 0.6,
      startV: 2,
      hints: ['The line has to reach 24 m at t = 4 s.', 'The slope you need is 24 ÷ 4.'],
      explanation: 'To pass through (4 s, 24 m), the slope must be 24 / 4 = 6 m/s — that is the velocity.',
      takeaway: 'Setting the slope sets the velocity.',
    },

    // ---------------- PRACTICE ----------------
    {
      id: 'pv-avg-numeric-2',
      type: 'numeric',
      phase: 'practice',
      concept: 'avg-velocity',
      prompt: 'A car covers a displacement of 240 m in 30 s. What is its average velocity?',
      answer: 8,
      unit: 'm/s',
      tolerance: 0.3,
      min: 0,
      max: 60,
      hints: ['v_avg = Δx / Δt.', '240 ÷ 30.'],
      explanation: 'v_avg = 240 / 30 = 8 m/s.',
      solution: ['v_avg = Δx / Δt = 240 / 30.', '= 8 m/s.'],
      takeaway: 'Same formula, any numbers.',
      game: { kind: 'track-trip', config: { velocity: 8 } },
    },
    {
      id: 'pv-graph-practice',
      type: 'interactive',
      phase: 'practice',
      widget: 'motion-graph',
      config: { velocity: 8 },
      title: 'Match a velocity to its slope',
      body: 'Quick hands-on break before the next questions. Set the velocity to 8, then 3, then −5, pressing Play each time. Try to picture the slope before the dot draws it.',
      keyPoints: [
        '8 m/s draws a steep upward line; 3 m/s a gentle one.',
        '−5 m/s slopes downhill (moving backward).',
        'The number on the slider IS the slope of the line.',
      ],
    },
    {
      id: 'pv-graph-numeric-2',
      type: 'numeric',
      phase: 'practice',
      concept: 'velocity-graph',
      prompt: 'On a position-time graph, position goes from 10 m to 70 m over 4 seconds. What is the velocity?',
      answer: 15,
      unit: 'm/s',
      tolerance: 0.3,
      min: 0,
      max: 60,
      hints: ['Rise = 70 − 10. Run = 4.', '60 ÷ 4.'],
      explanation: 'v = (70 − 10) / 4 = 60 / 4 = 15 m/s.',
      solution: ['Rise = 70 − 10 = 60 m.', 'v = 60 / 4.', '= 15 m/s.'],
      takeaway: 'Always subtract the starting position first.',
      game: { kind: 'motion-graph', config: { velocity: 15 } },
    },
    {
      id: 'pv-graph-target-2',
      type: 'graph-target',
      phase: 'practice',
      concept: 'avg-velocity',
      prompt: 'A trip covers 20 m in 5 s. Drag the velocity so your line reaches the target — that slope is the average velocity.',
      target: { t: 5, x: 20 },
      tolerance: 0.6,
      startV: 1,
      hints: ['Reach 20 m by t = 5 s.', '20 ÷ 5 is the slope you need.'],
      explanation: 'Average velocity = Δx/Δt = 20 / 5 = 4 m/s, the slope that hits (5 s, 20 m).',
      takeaway: 'Average velocity is the slope from start to end.',
    },
    {
      id: 'pv-plot-1',
      type: 'plot-position',
      phase: 'practice',
      concept: 'displacement',
      prompt: 'An object starts at 0 and moves at 7 m/s. Drag the marker to where it is after 5 seconds.',
      velocity: 7,
      time: 5,
      tolerance: 2,
      max: 50,
      hints: ['Position covered = velocity × time.', '7 × 5 is where it ends up.'],
      explanation: 'Distance covered = v·t = 7 × 5 = 35 m, so the object sits at the 35 m mark.',
      takeaway: 'At constant velocity, position = v · t.',
    },
    {
      id: 'pv-roundtrip',
      type: 'predict',
      phase: 'practice',
      concept: 'displacement',
      prompt:
        'A runner does one full lap of a 400 m track and stops exactly where they started, taking 80 s. What is their average VELOCITY?',
      choices: [
        { id: '5', label: '5 m/s' },
        { id: '0', label: '0 m/s' },
        { id: '400', label: '400 m/s' },
      ],
      correctId: '0',
      perChoiceFeedback: {
        '5': 'That is the average SPEED (400 m of distance ÷ 80 s). Velocity uses displacement.',
        '0': 'Exactly. They finished where they started, so displacement is 0 — and 0 ÷ 80 = 0.',
        '400': 'That mixes up the numbers; check the units and the formula.',
      },
      explanation:
        'Displacement for a full lap is 0 (start = finish), so average velocity = 0 / 80 = 0 m/s. Average speed, by contrast, is 400 / 80 = 5 m/s.',
      takeaway: 'Round trip: average velocity is zero, even though you moved.',
      game: { kind: 'round-trip', config: { speed: 5 } },
    },
    {
      id: 'pv-zero-velocity-concept',
      type: 'concept',
      phase: 'practice',
      concept: 'avg-velocity',
      title: 'How can average velocity be zero?',
      body: 'On a round trip you clearly moved — yet your average velocity is zero. That is the whole point of displacement: it only cares about start and end, not the path between. Average speed stays positive; average velocity can vanish.',
      keyPoints: [
        'Average speed uses distance — positive whenever you moved.',
        'Average velocity uses displacement — zero for a round trip.',
        'Direction is exactly what makes the two differ.',
      ],
    },
    {
      id: 'pv-speed-numeric',
      type: 'numeric',
      phase: 'practice',
      concept: 'avg-velocity',
      prompt: 'A train travels 1500 m east in 60 s. What is its average velocity (east is positive)?',
      answer: 25,
      unit: 'm/s',
      tolerance: 0.5,
      min: 0,
      max: 100,
      hints: ['v_avg = Δx / Δt.', '1500 ÷ 60.'],
      explanation: 'v_avg = 1500 / 60 = 25 m/s east.',
      solution: ['v_avg = 1500 / 60.', '= 25 m/s (east).'],
      takeaway: 'Direction (east) rides along with the number.',
      game: { kind: 'motion-graph', config: { velocity: 25 } },
    },

    {
      id: 'pv-graph-recap',
      type: 'interactive',
      phase: 'master',
      widget: 'motion-graph',
      config: { velocity: -5 },
      title: 'One last look before recall',
      body: 'A negative velocity one more time — watch the line head downhill, meaning the object moves back toward the start. Then take on the final questions from memory.',
      keyPoints: ['Downhill line = moving backward.', 'Flat line = at rest.', 'Steeper line = faster, in either direction.'],
    },

    // ---------------- MASTER ----------------
    {
      id: 'pv-recall-1',
      type: 'recall',
      phase: 'master',
      concept: 'speed-vs-velocity',
      prompt: 'From memory: what does velocity have that speed does not?',
      choices: [
        { id: 'size', label: 'A bigger number' },
        { id: 'dir', label: 'A direction' },
        { id: 'unit', label: 'Different units' },
      ],
      correctId: 'dir',
      explanation: 'Velocity is speed plus a direction. Same units (m/s), but velocity points somewhere.',
      takeaway: 'Velocity = speed + direction.',
      game: { kind: 'two-runners', config: { v1: 6, v2: -6 } },
    },
    {
      id: 'pv-recall-2',
      type: 'recall',
      phase: 'master',
      concept: 'avg-velocity',
      prompt: 'From memory: average velocity equals which of these?',
      choices: [
        { id: 'dist', label: 'Total distance ÷ time' },
        { id: 'disp', label: 'Displacement ÷ time' },
        { id: 'speed', label: 'Top speed ÷ 2' },
      ],
      correctId: 'disp',
      explanation: 'Average velocity = displacement ÷ time. Using distance instead would give average speed.',
      takeaway: 'It is displacement over time — direction included.',
      game: { kind: 'track-trip', config: { velocity: 6 } },
    },
    {
      id: 'pv-synthesis',
      type: 'mcq',
      phase: 'master',
      concept: 'velocity-graph',
      prompt: 'A position-time graph shows a perfectly flat horizontal line for 10 seconds. What is happening?',
      choices: [
        { id: 'fast', label: 'The object is moving very fast' },
        { id: 'rest', label: 'The object is at rest' },
        { id: 'back', label: 'The object is moving backward' },
      ],
      correctId: 'rest',
      perChoiceFeedback: {
        fast: 'Fast would be a steep line. Flat means the position is not changing.',
        rest: 'Right — no change in position means zero slope, zero velocity: at rest.',
        back: 'Backward would slope downhill. Flat is no motion at all.',
      },
      explanation: 'A flat position-time line has zero slope, so the velocity is zero — the object is standing still.',
      takeaway: 'Flat line = zero velocity = at rest.',
      game: { kind: 'motion-graph', config: { velocity: 0 } },
    },
  ],
}
