// Orchestrates practice-problem generation. Order of preference:
//   1. Ask the AI for a scenario, then VERIFY/compute the answer with the engine.
//   2. If AI is off, slow, or keeps proposing nonsense, fall back to an authored
//      template whose answer is also engine-computed.
// Either way the learner gets a fresh, correct numeric problem -- so Practice
// mode is fully functional with AI turned off.

import type { ConceptId, NumericStep, Step } from '../../types/content'
import type { GenDifficulty, GenQuantity } from './types'
import { requestProblemSpec } from './client'
import { buildVerifiedProblem, computeQuantity } from './verify'
import { difficultyForScore } from '../mastery'
import { conceptProblem, hasConceptGenerator } from './conceptProblems'

// Projectile-motion concepts are generated by the AI and then verified against
// the physics engine. The rest are produced deterministically (conceptProblems).
const PROJECTILE_CONCEPTS: ConceptId[] = [
  'components',
  'trajectory-shape',
  'angle-range',
  'range-reasoning',
  'complementary-angles',
]

// Every concept in the course can be drilled in Practice, grouped by lesson.
export const PRACTICE_CONCEPTS: ConceptId[] = [
  // Position & Velocity
  'speed-vs-velocity',
  'displacement',
  'avg-velocity',
  'velocity-graph',
  // Free Fall & Gravity
  'free-fall-rate',
  'gravity-accel',
  'fall-distance',
  // Projectile Motion
  'gravity-independence',
  'components',
  'trajectory-shape',
  // Range & aiming
  'angle-range',
  'range-reasoning',
  'complementary-angles',
]

const QUANTITIES_FOR: Partial<Record<ConceptId, GenQuantity[]>> = {
  components: ['vx', 'vy'],
  'trajectory-shape': ['timeOfFlight', 'maxHeight'],
  'range-reasoning': ['range'],
  'angle-range': ['range'],
  'complementary-angles': ['range'],
}

function allowedQuantities(concept: ConceptId): GenQuantity[] {
  return QUANTITIES_FOR[concept] ?? ['range']
}

const QUANTITY_QUESTION: Record<GenQuantity, string> = {
  range: 'how far (horizontally) does it land from the launch point',
  maxHeight: 'how high does it reach at the peak of its arc',
  timeOfFlight: 'how many seconds does it stay in the air',
  vx: 'what is its sideways speed v_x',
  vy: 'what is its starting upward speed v_y',
}

function randInt(min: number, max: number): number {
  return Math.floor(min + Math.random() * (max - min + 1))
}

/** Difficulty shapes the launch envelope: easier problems use rounder numbers. */
function paramsFor(difficulty: GenDifficulty): { angleDeg: number; speed: number } {
  if (difficulty === 'easy') {
    return { angleDeg: [30, 45, 60][randInt(0, 2)], speed: [10, 15, 20][randInt(0, 2)] }
  }
  if (difficulty === 'medium') {
    return { angleDeg: randInt(20, 65), speed: randInt(12, 28) }
  }
  return { angleDeg: randInt(15, 75), speed: randInt(10, 40) }
}

function round1(n: number): number {
  return Math.round(n * 10) / 10
}

/** A deterministic, engine-correct problem used when AI is unavailable. */
function authoredProblem(
  concept: ConceptId,
  difficulty: GenDifficulty,
  avoid: Set<string>,
): NumericStep {
  const gravity = 9.8
  const quantities = allowedQuantities(concept)
  let angleDeg = 45
  let speed = 20
  let quantity: GenQuantity = quantities[0]
  // A few tries to avoid an exact repeat of the last problems.
  for (let i = 0; i < 8; i++) {
    const p = paramsFor(difficulty)
    quantity = quantities[randInt(0, quantities.length - 1)]
    const sig = `${p.angleDeg}/${p.speed}/${quantity}`
    if (!avoid.has(sig)) {
      angleDeg = p.angleDeg
      speed = p.speed
      break
    }
    angleDeg = p.angleDeg
    speed = p.speed
  }

  const value = round1(computeQuantity(quantity, angleDeg, speed, gravity))
  const unit = quantity === 'timeOfFlight' ? 's' : quantity.startsWith('v') ? 'm/s' : 'm'
  const tol = Math.max(quantity === 'timeOfFlight' ? 0.15 : 0.5, round1(value * 0.04))

  return {
    id: `gen-${concept}-${Math.random().toString(36).slice(2, 9)}`,
    type: 'numeric',
    concept,
    phase: 'practice',
    prompt: `A projectile is launched at ${angleDeg}° with a speed of ${speed} m/s (g = ${gravity}). To the nearest tenth, ${QUANTITY_QUESTION[quantity]}?`,
    answer: value,
    unit,
    tolerance: tol,
    min: 0,
    max: quantity === 'timeOfFlight' ? 20 : quantity === 'range' ? 250 : 60,
    hints: [
      'Split the launch into sideways (v·cosθ) and upward (v·sinθ) parts first.',
      quantity === 'range'
        ? 'Range = v_x times the total time in the air.'
        : quantity === 'timeOfFlight'
          ? 'Time aloft t = 2·v_y / g.'
          : quantity === 'maxHeight'
            ? 'Peak height H = v_y² / (2g).'
            : 'Use the component formula directly.',
    ],
    explanation: `Working it through with g = ${gravity}, the answer is ${value} ${unit}.`,
  }
}

export interface NextProblemResult {
  step: Step
  /** 'ai' when the scenario came from the model (answer still engine-computed). */
  source: 'ai' | 'authored'
  signature: string
}

// Every practice step must carry an explicit game so StepView never falls back
// to its random widget pool (the source of the buggy/mismatched practice games).
// Concept generators attach a lesson-matched, spoiler-safe game; anything that
// doesn't (e.g. projectile numerics, whose sims would reveal the answer) gets
// no game rather than a random one.
function ensureGame(step: Step): Step {
  if (!step.game) step.game = { kind: 'none' }
  return step
}

/**
 * Produce the next verified practice problem for a concept. Tries the AI up to
 * `maxTries` times (rejecting any spec that fails engine verification or repeats
 * a recent scenario), then falls back to an authored template.
 */
export async function nextPracticeProblem(
  concept: ConceptId,
  score: number | undefined,
  avoid: string[] = [],
  maxTries = 2,
): Promise<NextProblemResult> {
  const avoidSet = new Set(avoid)
  const allowed = allowedQuantities(concept)
  const difficulty: GenDifficulty = difficultyForScore(score)

  // Non-projectile concepts are generated deterministically (always correct).
  if (!PROJECTILE_CONCEPTS.includes(concept) && hasConceptGenerator(concept)) {
    const step = conceptProblem(concept, difficulty)
    if (step) return { step: ensureGame(step), source: 'authored', signature: step.id }
  }

  for (let attempt = 0; attempt < maxTries; attempt++) {
    const spec = await requestProblemSpec({
      concept,
      difficulty,
      allowedQuantities: allowed,
      avoid,
    })
    if (!spec) break
    const verified = buildVerifiedProblem(spec, concept)
    if (verified && !avoidSet.has(verified.signature)) {
      return { step: ensureGame(verified.step), source: 'ai', signature: verified.signature }
    }
  }

  const step = authoredProblem(concept, difficulty, avoidSet)
  const sig = step.prompt
  return { step: ensureGame(step), source: 'authored', signature: sig }
}
